name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build jekyll and deploy to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install ruby and build site
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - run: bundle exec jekyll build
      - run: npm install -g surge
      - run: surge ./_site ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
